# Generated by Django 2.0 on 2018-10-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task_name', models.CharField(blank=True, max_length=255, null=True)),
                ('Employee_name', models.CharField(blank=True, max_length=255, null=True)),
                ('Employee_Id', models.IntegerField(unique=True)),
                ('mobile_number', models.IntegerField(unique=True)),
                ('created_date', models.DateTimeField()),
            ],
        ),
    ]
